[package]
name = "plugin-native"
version = "0.1.0"
authors = ["Frixuu <kontakt@lukasz.xyz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]

[profile.release]
codegen-units = 1
lto = true
